package transport

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
)

// ServiceDesc is a description of an endpoints' collection.
// These functions should be autogenerated by protoc-gen-goclay.
type ServiceDesc interface {
	RegisterGRPC(*grpc.Server)
	RegisterHTTP(ctx context.Context, mux *runtime.ServeMux) error
	SwaggerDef() []byte
}

// ConfigurableServiceDesc is implemented by configurable ServiceDescs.
type ConfigurableServiceDesc interface {
	Apply(...DescOption)
}
