package transport

import (
	"context"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/not-for-prod/clay/transport/swagger"
	"google.golang.org/grpc"
)

// Service is a registerable collection of endpoints.
// These functions should be autogenerated by protoc-gen-goclay.
type Service interface {
	GetDescription() ServiceDesc
}

// ServiceDesc is a description of an endpoints' collection.
// These functions should be autogenerated by protoc-gen-goclay.
type ServiceDesc interface {
	RegisterGRPC(*grpc.Server)
	RegisterHTTP(ctx context.Context, mux *runtime.ServeMux) error
	SwaggerDef(options ...swagger.Option) []byte
}

// Router routes HTTP requests around.
type Router interface {
	http.Handler
	Handle(pattern string, h http.Handler)
}

// ConfigurableServiceDesc is implemented by configurable ServiceDescs.
type ConfigurableServiceDesc interface {
	Apply(...DescOption)
}
