// Code generated by protoc-gen-goclay, but you can (must) modify it.
// source: pb/sum.proto

package sum

import (
	"context"

	"github.com/pkg/errors"
	desc "github.com/utrack/clay/doc/example/pb"
	"google.golang.org/genproto/googleapis/rpc/errdetails"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

func (i *SummatorImplementation) Sum(ctx context.Context, req *desc.SumRequest) (*desc.SumResponse, error) {
	session := metadata.ValueFromIncomingContext(ctx, "summator-session")
	if len(session) == 0 {
		// grpc-gateway detailed errors
		st, err := status.New(
			codes.Unauthenticated,
			"summator-session Cookie not set",
		).WithDetails(
			&errdetails.ErrorInfo{
				Reason:   "no Cookie found",
				Domain:   "Summator",
				Metadata: map[string]string{},
			},
		)
		if err != nil {
			return nil, status.Error(codes.Internal, "something went wrong")
		}

		return nil, st.Err()
	}

	if req.GetA() == 0 {
		return nil, errors.New("a is zero")
	}

	// Panic handling example
	if req.GetB().B == 65536 {
		panic(errors.New("we've got a problem; the panic is planned to happen"))
	}

	// Cookie behaviour example
	if req.GetB().B == 65538 {

	}

	sum := req.GetA() + req.GetB().B

	return &desc.SumResponse{
		Sum: sum,
	}, nil
}
