// Code generated by protoc-gen-goclay, but you can (must) modify it.
// source: pb/sum.proto

package sum

import (
	desc "github.com/utrack/clay/doc/example/pb"
)

type SummatorImplementation struct {
	desc.UnimplementedSummatorServer
}

// NewSummator create new SummatorImplementation
func NewSummator() *SummatorImplementation {
	return &SummatorImplementation{}
}
